blueprint:
  name: Schalter mit Licht synchronisieren (Asymmetrisch)
  description: >
    Schaltet spezifische Lichter EIN, aber ALLE Lichter in einem
    zugehörigen Bereich AUS. Basiert auf einer Steuer-Entität.

    Nützlich, wenn ein Schalter (z.B. Shelly) nur die Hauptbeleuchtung
    einschalten soll, aber beim Verlassen des Raumes (AUS)
    sicherstellen soll, dass auch alle Stimmungs-Lichter ausgehen.
  domain: automation

  input:
    control_entity:
      name: Steuer-Entität (Schalter)
      description: Die Entität (z.B. switch.shelly), die den Zustand 'on'/'off' vorgibt.
      selector:
        entity: {}

    target_lights_on:
      name: Ziel-Lichter (Einschalten)
      description: Die spezifischen Lichter, die eingeschaltet werden sollen.
      selector:
        target:
          domain: light

    target_area_off:
      name: Ziel-Bereich (Ausschalten)
      description: ALLE Lichter in diesem Bereich werden ausgeschaltet.
      selector:
        area: {}

    brightness_on:
      name: (Optional) Helligkeit beim Einschalten
      description: Ein Wert von 1-100.
      selector:
        number:
          min: 1
          max: 100
          mode: slider
      default: {} # Wichtig: Leeres Default macht es optional

    color_temp_on:
      name: (Optional) Farbtemperatur beim Einschalten
      description: In Kelvin (z.B. 2700 für Warmweiß, 6500 für Kaltweiß).
      selector:
        number:
          min: 2000
          max: 6500
          mode: slider
      default: {} # Wichtig: Leeres Default macht es optional

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input control_entity
    to: 'on'
    id: 'turn_on'
  - platform: state
    entity_id: !input control_entity
    to: 'off'
    id: 'turn_off'

action:
  - choose:
    - conditions:
        - condition: trigger
          id: 'turn_on'
      sequence:
        - service: light.turn_on
          target: !input target_lights_on  # <-- Nutzt das "EIN"-Ziel
          data:
            brightness_pct: !input brightness_on
            color_temp_kelvin: !input color_temp_on

    # AKTION FÜR "AUS"
    - conditions:
        - condition: trigger
          id: 'turn_off'
      sequence:
        - service: light.turn_off
          target:
            area_id: !input target_area_off # <-- Nutzt das "AUS"-Ziel (Bereich)
          data: {}
