---
blueprint:
  name: Hoymiles HMS Controler
  description: >-
    # Hoymiles HMS Controler

    Diese Automation kontrolliert das Einspeiseverhalten eines HMS Wechselrichters.
    Als Bedingung müssen HMS Sensoren in Home Assistant angelegt werden zum Beispiel
    über MQTT. Ausserdem müssen Schalter erstellt werden um diverse Werte zu steuern.

    ## Beispielhaft ein paar Ideen, wie man an die Daten im Homeassistant bekommen kann

    [OpenDTU](https://github.com/tbnobody/OpenDTU) als Start und sehr guter MQTT
    Unterstützung.

    [OpenDTU on Battery](https://github.com/helgeerbe/OpenDTU-OnBattery) auch wenn man
    dann diese Steuerung nicht benötigt.

    ## Das Original dieses Blueprint liegt unter
    [https://git.zyria.de/pyrox/home-assistant-blueprints.git](https://git.zyria.de/pyrox/home-assistant-blueprints.git)

  source_url: https://github.com/ricariel/home-assistant-blueprints/blob/main/blueprints/automation/ricariel/control-hms.yaml
  domain: automation
  author: Fabrice Kirchner
  input:

    battery_level_sensor:
      name: Batterieladestand Sensor
      description: Ein Sensor, welchen den aktuellen Batterieladestand
        wiedergibt. Bei mir electricLevel
      selector:
        entity:
          domain:
          - sensor
          multiple: false
          filter:
            domain: sensor
            device_class: battery

    output_limit_number:
      name: Einspeiselimit Schalter
      description: Eine Number zum Einstellen des Einspeiselimit. Bei mir
        outputLimit
      selector:
        entity:
          domain:
          - number
          multiple: false
          filter:
            domain: number
            device_class: power

    output_home_power:
      name: Aktuelle Einspeisung Sensor
      description: Was der Hub aktuell ins Haus abgibt. Dies inkludiert auch
        Solarleistung. Bei mir outputHomePower
      selector:
        entity:
          domain:
          - sensor
          multiple: false
          filter:
            domain: sensor
            device_class: power

    smartmeter_input_sensor:
      name: Smartmeter Power Sensor
      description: Aktueller Verbrauch (Wirkleistung) in Watt
      selector:
        entity:
          domain:
          - sensor
          multiple: false
          filter:
            domain: sensor
            device_class: power

    alternative_power_sensor:
      name: Alternativer Power Sensor
      description: Dieser Sensor sollte in etwa den Wert eines nicht
        gedrosselten Solarpanel in Watt ausgeben. Dies wird benutzt für eine
        alternative Bypass Implementierung für den Hub. Bei mir ist es ein
        Panel, was nicht am Solarflow hängt
      selector:
        entity:
          domain:
          - sensor
          multiple: false
          filter:
            domain: sensor
            device_class: power

    num_request_limit:
      name: Anfragelimit in Sekunden
      description: Wie oft soll die Automation mindestens warten bis erneut
        geregelt wird.
      default: 10
      selector:
        number:
          min: 1
          mode: box

    num_min_limit:
      name: Minimales Limit beim Regeln
      description: Manche Wechselrichter benötigen eine minimale Leistung
        um gut zu funktionieren.
      default: 50
      selector:
        number:
          min: 0
          mode: box


    num_upper_power_acceptance:
      name: Oberes akzeptables Limit unter dem Wir nicht regeln
      description: Die Steuerung versucht die Einspeisung zwischen zwei
        Punkten zu halten, wenn nicht genügend Solarenergie kommt. Dies ist
        der obere davon.
      default: 10
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "W"
          mode: slider

    num_lower_power_acceptance:
      name: Unteres akzeptables Limit unter dem Wir nicht regeln
      description: Die Steuerung versucht die Einspeisung zwischen zwei
        Punkten zu halten, wenn nicht genügend Solarenergie kommt. Dies ist
        der untere davon.
      default: '-10'
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "W"
          mode: slider

    num_inverter_limit:
      name: Sensor für das maximale Limit des Wechselrichter
      description: Hier ist der Sensor für das maximale Limit des Hubs
        anzugeben, wieviel eingespeist werden darf. Hast du zum Beispiel
        einen Wechselrichter mit Limit 300Watt je MPTT aber den Hub an zwei
        MPTT angeschlossen, kannst du hier 600 angeben. Diese Einstellung
        wird normal über die Zendure App bei der Einrichtung gesetzt. Bei
        mir inverseMaxPower
      default: 800
      selector:
        number:
          min: 0
          max: 2000
          mode: slider

    num_bat_full:
      name: Wann ist die Batterie als voll anzusehen
      description: Ein Wert zwischen 0 und 100 wann die Batterie als voll gilt.
      default: 100
      selector:
        number:
          min: 0
          max: 100
          mode: slider

    num_bypass:
      name: Prozentualer Anteil im emulierten Bypass
      description: Wieviel soll dieser Hub zur Stromlieferung an das Haus
        beitragen, wenn der Akku voll ist. Dies ist ein emulierter Bypass
        und abhängig von der externen Panelleistung.
      default: 90
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

    num_panels:
      name: Anzahl der Anschlüsse am Wechselrichter
      description: Hier gibst du die Anzahl der blegten Anschlüsse am
        Wechselrichter an.
      default: 1
      selector:
        number:
          mode: box



variables:
  battery_level_sensor: !input battery_level_sensor
  num_request_limit: !input num_request_limit
  output_home_power: !input output_home_power
  output_limit_number: !input output_limit_number
  smartmeter_input_sensor: !input smartmeter_input_sensor
  num_min_limit: !input num_min_limit
  num_lower_power_acceptance: !input num_lower_power_acceptance
  num_upper_power_acceptance: !input num_upper_power_acceptance
  num_inverter_limit: !input num_inverter_limit
  alternative_power_sensor: !input alternative_power_sensor
  num_bat_full: !input num_bat_full
  num_bypass: !input num_bypass
  num_panels: !input num_panels

trigger:
  - platform: state
    entity_id:
      - !input smartmeter_input_sensor

condition:
  - condition: template
    value_template: '{{ now() - state_attr(this.entity_id, "last_triggered") | default(as_datetime(0), true) > timedelta(seconds=num_request_limit) }}'

action:
  - variables:
      # is battery full?
      bat_full: |-
        {{ ((states(battery_level_sensor)|int(0) >= num_bat_full|int(0))) }}


      # boost function if demand is higher than 30% of maximum
      min_limit_boost: |-
        {{
          num_inverter_limit|int(0) if num_inverter_limit|int(0)/0.3 < states(smartmeter_input_sensor)|int(0) else 0
        }}

      min_limit_bat_full: |-
        {{
          (states(alternative_power_sensor)|int(0)/100*num_bypass)|int(0) if bat_full else 0|int(0)
        }}

      # calculate min_limit
      min_limit: |-
        {{
          max([
            num_min_limit,
            min_limit_bat_full*num_panels,
            min_limit_boost
          ])|int(0)
        }}

      # calculate max_limit
      max_limit: |-
        {{
          min([
            ((-500+states(smartmeter_input_sensor)|int(0))*-1),
            num_inverter_limit|int(0)
            ])
        }}

      # get target power
      target_power: |-
        {{
          ((num_lower_power_acceptance|int(0)+num_upper_power_acceptance|int(0))/2)
        }}

      # get demand and shrink to local instance
      requested_power: |-
        {{
          (
              states(output_home_power)|float(0)|int(0)+
              states(smartmeter_input_sensor)|int(0)-
              target_power|int(0)
          )|int(0)
        }}


      min_inverter_limit: "{{
        num_inverter_limit|int(0) if num_inverter_limit|int(0)*0.17 < requested_power|int(0) else 0
      }}"

      # calculate limit
      limit: |-
        {{
          min([
            max([
              min_inverter_limit,
              requested_power,
              min_limit
            ]),
            max_limit
          ])
        }}

  # Stop if nothing to do
  - if:
      - condition: template
        value_template: |-
          {{
            limit|int(0) == states(output_limit_number)|int(0)
          }}
    then:
      - stop: "Stoppping loop. Nothing to set"

  # Set limit
  - service: number.set_value
    target:
      entity_id:
        - !input output_limit_number
    metadata: {}
    data:
      value: "{{ limit }}"

mode: single
max_exceeded: silent
trace:
  stored_traces: 30
